theme: jekyll-theme-cayman
title: Coursera HTML5, CSS and JavaScript Course
description: Validating the HTML5, CSS, and JavaScript course from Coursera which probably will be assigned to the members of my team.
